workflows:
  ios-build:
    name: SCEMS iOS Dry Build
    environment:
      vars:
        APP_NAME: "SCEMS Protocols"
    scripts:
      - name: Sync Capacitor (manually assume iOS added)
        script: |
          npx cap sync ios || true
      - name: Build iOS app (no signing)
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release | xcpretty
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.app
