
workflows:
  ios-build:
    name: SCEMS iOS Dry Build
    environment:
      vars:
        APP_NAME: "SCEMS Protocols"
    scripts:
      - name: Install Node.js dependencies
        script: |
          npm install
      - name: Add iOS platform
        script: |
          npx cap add ios
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app (no signing)
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release | xcpretty
    artifacts:
      - ios/build/Build/Products/Release-iphoneos/*.app
